spring.application.name=application
spring.profiles.active=dev
#---

#===========================
#Dev Proile
#==========================

#---
spring.config.activate.on-profile=dev
spring.r2dbc.url= r2dbc:postgresql://localhost:5433/prueba
spring.r2dbc.username=postgres
spring.r2dbc.password=123
#---

#===========================
#Docker Proile
#==========================

#---
spring.config.activate.on-profile=docker
spring.r2dbc.url= ${DATABASE_URL}
spring.r2dbc.username=${DATABASE_USERNAME}
spring.r2dbc.password=${DATABASE_PASSWORD}
#---

#===========================
#Production Proile
#==========================

#---
spring.config.activate.on-profile=production
spring.r2dbc.url= ${DATABASE_URL}
spring.r2dbc.username= ${DATABASE_USERNAME}
spring.r2dbc.password= ${DATABASE_PASSWORD}
#---